### PR TITLE
Add Dockerfile

### PR DESCRIPTION
**Pull request by ghosind**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

Add the dockerfile to dockerize the dashboard.

**Which issue(s) this PR fixes**:

For #27 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Review by wbc6080 — COMMENTED** [review]
I have a small question. The login interface requires a token. How to obtain this token?

**Comment by ghosind** [comment]
> I have a small question. The login interface requires a token. How to obtain this token?

Hi @wbc6080 , It requires a k8s service account with the admin cluster role, and uses `kubectl create token <service-account>` command to obtain the token.

there is an example to obtain a token:

```sh
kubectl create serviceaccount test-user -n kube-system
kubectl create clusterrolebinding test-user-binding --clusterrole=cluster-admin --serviceaccount=kube-system:test-user -n kube-system
kubectl create token test-user --namespace kube-system
```

**Review by wbc6080 — COMMENTED** [review]
OK, thanks.
/lgtm

**Review by fisherxu — COMMENTED** [review]
/approve

**Pull request merged**
