### PR TITLE
refactor: new dashboard with Next.js and MUI.

### PR DESCRIPTION
**Pull request by ghosind**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

A new dashboard with Next.js and Material UI.

**Which issue(s) this PR fixes**:

For #22 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Review by Shelley-BaoYue — COMMENTED** [review]
/lgtm

**Review by wbc6080 — COMMENTED** [review]
/lgtm

**Review by fisherxu — COMMENTED** [review]
/approve

**Pull request merged**
